### ISSUE TITLE
Grunt-browserify doesn't support parcelify

### ISSUE THREAD

**Issue by poonwu** [wrong-theory/riron-client#2]
[parcelify](https://github.com/rotundasoftware/parcelify) is not a vanilla plugin for [grunt-browserify](https://github.com/jmreidy/grunt-browserify). What should I do?

**Comment by ssabpisa** [comment]
Arent u at church?

**Comment by poonwu** [comment]
@ssabpisa , tho that's irrelevant to this issue, today is quite fast + I didn't have a big lunch with all my relatives.

**Comment by ssabpisa** [comment]
wanna come to Double A?

**Comment by poonwu** [comment]
@ssabpisa too far and it's raining, prolly meeting at central emb is better?

**Comment by ssabpisa** [comment]
cuz i probably wont go to emb. meeting but I can pick u up at sathorn bts if u want to come to dblA. Or u can skype in.

**Comment by ssabpisa** [comment]
btw what the heck is parcelify

**Comment by poonwu** [comment]
@ssabpisa Dunno about that, maybe skype it is a good choice? Why aren't going to emb. meeting anyway (though, I don't really know the agenda for going there anyway)? 

Parcelify is browserify for css, so u just `require('bootstrap')` and booom `bundle.css` with bootstrap.

**Comment by ssabpisa** [comment]
I have plans haha - im in this general meeting . Ps: its fcking sunny out

**Comment by poonwu** [comment]
@ssabpisa Ok, i'll just skype with screenshare if you want. Since i have my tablet, i can draw diagrams.

PS. It's raining where I am though

**Comment by poonwu** [comment]
@ssabpisa I'll just call your skype, since i believe everybody is there except me?

**Comment by ssabpisa** [comment]
sure sure. they went out for lunch.

**Comment by poonwu** [comment]
@ssabpisa calling

**Comment by poonwu** [comment]
Should we create custom task that use native browserify with parcelify?

**Comment by poonwu** [comment]
Workaround is done on a2c598

**Comment by poonwu** [comment]
a2c59839
